"""followers

Revision ID: 91413d9a74a5
Revises: df86d379ee0c
Create Date: 2018-10-03 20:20:36.927299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91413d9a74a5'
down_revision = 'df86d379ee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
